### PR TITLE
DRUP-783 #ready added collection field ask me about, deleted staff expertise field, css changes

### PR DESCRIPTION
**Pull request by emb03**
@z3cka plz merge and test locally, if all good deploy to test. Thank you!!!!

### CODE REVIEW

**Comment by akohler** [comment]
Is there data in the staff expertise field, which might cause deployment complications since we'll have to delete that field from the database?  @z3cka : if you encounter any problems deploying to test, please document the fix I'll need to do for staging/production - I've done it before but might as well benefit from you going first :)

**Comment by z3cka** [comment]
@akohler yes, this will delete some field data —data that we don't care about... this can be problematic via features. I'm going to test on my local with a backup from production. Will then document experience and repeat on test.

**Comment by emb03** [comment]
@akohler No, we need to keep it, plz don't delete, using it in Field Collection, just removed it from content type, sorry about confusing wording in commit message

**Comment by z3cka** [comment]
So, features will never delete data: https://www.drupal.org/node/649298#comment-7710069 so, this field needs to be removed with a handy drush command like the one found here: http://www.hook42.com/blog/deleting-drupal-field-saved-features

I will look into building this into our deploy scripts or looking at this as a REAL reason to see if using something like [Kraftwagen](http://kraftwagen.org/).

**Comment by emb03** [comment]
From the what do I know dept.:
This sounds easier....https://api.drupal.org/api/drupal/modules!field!field.crud.inc/function/field_delete_field/7

**Comment by z3cka** [comment]
@eb and I just figured out a great way to automate the removal of this field instance:
```php
/**
 * Implements hook_update_N() - removes the body field instance from the Staff Profile content type.
 */
function uclalib_staff_profile_update_7100(&$sandbox) {
  if ($instance = field_info_instance('node', 'body', 'staff_profile')) {
    field_delete_instance($instance);
  }
}
```
This will get run in step 4 of the `drupal_copy_code` deployment script. So, we feel this is simple and somewhat automated.

Another PR coming.

**Comment by akohler** [comment]
One minor issue/convention: it's my understanding that the update number should correspond to the version of the module, which per the info file is currently version = 7.x-1.3

Not sure if it matters (or if I'm even right), but if so, should the update_nnnn be 7300?

**Comment by z3cka** [comment]
from: https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_update_N/7

> * **mymodule_update_7100()**: This is the first update to get the database ready to run mymodule 7.x-1.*.

So I think in this case 7100() is correct.

**Comment by akohler** [comment]
@z3cka Thanks for the version clarification, makes sense.

**Comment by z3cka** [comment]
all of the changes in #138 are in #139. closing.

**Pull request closed without merging**
