### PR TITLE
Remove beta from versions for release to production.

### PR DESCRIPTION
**Pull request by akohler**
commit afa399fd67b50ce6d7a2185ed62d89545e285a7d
Author: Andy Kohler <akohler@library.ucla.edu>
Date:   Thu Mar 31 11:33:30 2016 -0800

    DRUP-865: Bump version for prod release

commit d36e1a90808aac3bcb697cababf716ded5eb375a
Author: Andy Kohler <akohler@library.ucla.edu>
Date:   Thu Mar 31 11:32:15 2016 -0800

    DRUP-858: Bump version for prod release

commit 7c20be6985d13867c41f26fdee366f0fac9bc4dc
Author: Andy Kohler <akohler@library.ucla.edu>
Date:   Thu Mar 31 11:31:15 2016 -0800

    DRUP-882: Bump version for prod release

### CODE REVIEW

**Comment by akohler** [comment]
@z3cka Please do the usual.... FYI, I'm using a label "Deployable" to help me keep track of what's intended to go to prod next.  The label's on the master/test PRs to help me find the ones which will need staging PRs; I'll relabel accordingly when I make the staging PRs.  Hope that makes sense.

**Comment by z3cka** [comment]
nice, good idea

**Comment by z3cka** [comment]
Looks good; deploying to `www-test` now.

**Comment by z3cka** [comment]
`Copying of code from here to www-test2.library.ucla.edu is complete.`

**Pull request merged**
