### PR TITLE
UCLALIB-222: Mobile Responsive theme overhaul

### PR DESCRIPTION
**Pull request by jameswilson**
Currently the library.ucla.edu site works on desktop and tablets only.

This PR adds the basic functionality required for the site to become fully fluid-responsive down to handheld devices.

### Tasks to execute when deploying:

* Revert all features to their default states.
* Fix theme settings for responsive compatibility. (see [Mobile Responsive Notes](https://bluespark.atlassian.net/wiki/display/UCLALIB/Responsive+Mobile+Redesign))
* Manually convert all custom-made tables inside the body field to responsive tables. (see [Mobile Responsive Notes](https://bluespark.atlassian.net/wiki/display/UCLALIB/Responsive+Mobile+Redesign))

### User Acceptance Testing

At this point, UAT is turned over to UCLALIB team. 

We have a page in confluence to list the locations that need to be QA'd here:
https://bluespark.atlassian.net/wiki/display/UCLALIB/Site+pages

Due to budget limitations we were unable to internally complete QA on mobile devices, so your review should focus on:

1) Use the [Site pages](https://bluespark.atlassian.net/wiki/display/UCLALIB/Site+pages) document as a guide. Add other important pages to the table if we've missed one.
2) Perform i-device testing, (ios8, ios9, iphone6 iphone6 plus) report the version used with any bugs.
3) other browsers from the compatibility list on https://bluespark.atlassian.net/browse/UCLALIB-223

When processing through the [Site pages](https://bluespark.atlassian.net/wiki/display/UCLALIB/Site+pages) document, please add to the "iphone" column a ❌  or a green check and the kind of device you tested on for each page. 
Eg, " ❌ ios9 iphone6"

### When filing a bug please:

1) Create a ticket in the Bluespark JIRA backlog and Bluespark team will estimate and prioritize and work them into a last sprint.
2) Link to the ticket in the Site pages doc in the "Notes" column beside the page that is modified.

/cc @z3cka @emb03 @lewisnyman @AThevenet

### CODE REVIEW

**Comment by z3cka** [comment]
hey @lewisnyman thanks for the commit. Are you working on our project this week? We were under the impression that you were off on another project. Let me know what your bandwidth looks like _(or have Ashleigh fill us in)_.

We plan to merge this PR today and continue QA on both your servers and ours. Let me know if you have more quick commits coming.

Thanks.

**Comment by lewisnyman** [comment]
@z3cka Hi! I'm officially off the project. I just had a little bit of spare time today to work on some low hanging fruit. No more commits from me. Good luck with the merge.

**Comment by z3cka** [comment]
@lewisnyman thanks for the quick response! Cheers.

**Comment by z3cka** [comment]
deploying to `www-test` now

**Comment by z3cka** [comment]
`Copying of code from here to www-test2.library.ucla.edu is complete.` so far, so good... time to revert some features

**Comment by z3cka** [comment]
Well, that went swimmingly! we are responsive!!! http://www-test.library.ucla.edu

**Pull request merged**
