### PR TITLE
WS-960 - cloned statsform into libraryweb-site for wwwtest

### PR DESCRIPTION
**Pull request by darrowcoucla**
Initial move to wwwtest to allow iPad testing and development of Shibboleth authentication.

### CODE REVIEW

**Comment by z3cka** [comment]
Pull requests this large need to be reviewed before they are merged.

**Comment by darrowcoucla** [comment]
Sorry, I did not realize a revuew was needed - should I hit the "revert" button?

**Comment by z3cka** [comment]
Yes, if you have not pulled it to www-test yes

**Comment by darrowcoucla** [comment]
This PR was not pulled into www-test.

**Comment by z3cka** [comment]
Now make another PR, same as this one, and assign the team as reviewers.

**Pull request merged**
