### PR TITLE
DRUP-675: in my haste I forgot yet another dependency, this adds the …

### PR DESCRIPTION
**Pull request by z3cka**
…http_client dependency for wsclient_rest module

to provide ORCID integration with OAuth.

@akohler ... this is what I get for waiting until the last minute on Saturday. This functionality is not actually needed until Monday, June 1st... but would like to test this in prod before then.  
Please deploy to www-test and I will test there and have a possible out of cycle deployment on Thursday night. **Thoughts**?

### CODE REVIEW

**Comment by akohler** [comment]
@z3cka Deployed to www-test.  We can do mid-week production deployment if necessary but Thur night gives just Fri to test in production, as opposed to standard Sat night deployment.

If www-test and prod are so different that we need to test in production, can we improve www-test instead?

**Comment by z3cka** [comment]
Testing in www-test is probably good enough, just want to have one run through in prod before the email announcement for the first batch goes out on Monday.

**Comment by akohler** [comment]
Up to you – if you decide you need production deployment before the weekend, just let me know.

**Comment by z3cka** [comment]
will do. thanks –roboAndy

**Pull request merged**
