### PR TITLE
Replace icomoon.com with icomoon.io

### PR DESCRIPTION
**Pull request by danielcgold**
Icomoon.com is some weird spammy site that beeps when you click it.

### CODE REVIEW

**Comment by tristanoneil** [comment]
:full_moon_with_face:

**Comment by z3cka** [comment]
thanks for the pull request. I noticed that the contrib module does not have this patch – https://www.drupal.org/project/icomoon 

While I will reject this change here. I will submit this change to the contrib module _(unless you want to)_. 

Thank you!

**Comment by z3cka** [comment]
I've submitted a patch the the Drupal module: https://www.drupal.org/node/2528352

Here's hoping the module maintainer accepts the patch, Thanks again.

**Comment by z3cka** [comment]
@danielcgold just curious, how did you come across this issue?

**Comment by danielcgold** [comment]
@z3cka I was really bored on a Friday. icomoon.com vs. icomoon.io is a known issue so I was searching gh for instances of that and fixing them.

**Pull request closed without merging**
