### PR TITLE
WS-428: Removed LCAS survey from site

### PR DESCRIPTION
**Pull request by akohler**
@z3cka Please review and merge, then back to me for deployment.  Thanks --Andy

### CODE REVIEW

**Comment by z3cka** [comment]
Very nice... I think this js was actually causing a bug and was going to bring it up, but now this fixes it! Just a thought, should we version our uclalib_omega theme? like, 7.x-1.0 ...

**Comment by akohler** [comment]
Certainly we can add a version number uclalib_omega, and probably should.  Is it 7.x-1.0 for version of our theme, or 7.x-4.2 to match version of the parent omega theme?

**Comment by z3cka** [comment]
I like 7.x-4.x to match omega 4. We can start with 7.x-4.2 if that makes sense –and the next revision can be 7.x-4.3 ... thoughts?

**Comment by akohler** [comment]
So we'd start uclalib_omega version at 7.x-4.2, increment as we revise it - but stay in 7.x-4.* to match parent omega version, until that goes to 7.x-5.x or 8.x-1.0 etc.?  Fine with me.

**Comment by z3cka** [comment]
yep. I'd like to do something like 7.x-4.2.x but that has some problems as semantic versioning does not exist is Drupal 7 land. Note, D8 will have semantic versioning. I don't know what that will look like for contib modules and themes. I imagine something like 4.2.x with a dep of Drupal 8.* ... or something like that. Here's more detail on the naming switch: https://www.drupal.org/node/1612910 *(only 211 comments to read, enjoy)*

**Pull request merged**
