### PR TITLE
WS-616: Added 24-hour information notice to YRL RC-Res, around lines:…

### PR DESCRIPTION
**Pull request by darrowcoucla**
WS-616: Added 24-hour information notice to YRL RC-Res around lines 641, 683, 1598, 1607

### CODE REVIEW

**Comment by akohler** [comment]
@darrowcoucla or @z3cka Has this PR been deployed and tested on www-test?  I think this needs to go into production this weekend, along with staff profile changes if they're ready.  Will one of you create a staging PR for me to deploy to production?

**Comment by z3cka** [comment]
No, has not gone to test yet. Pulling now (in about 10 minutes - going to show @darrowcoucla how that works). I will also create that deploy ticket.

**Comment by z3cka** [comment]
deploying now

**Comment by z3cka** [comment]
Copying of code from here to www-test2.library.ucla.edu is complete.

**Pull request merged**
