### PR TITLE
DRUP-1116: #awaiting adds multi field dependency to uclalib_bookplates, adds new icon to uclalib_architecture

### PR DESCRIPTION
**Pull request by emb03**
@z3cka .info has same version number (2.9) as Andy's commit so should not conflict, Anne is hoping that this will be done by Monday, so it at all possible, please queue for prod before then. Thx.

### CODE REVIEW

**Comment by z3cka** [comment]
looks to be missing changes from #380

**Comment by emb03** [comment]
@z3cka I didn't do Andy's I thought you would do that.

**Comment by emb03** [comment]
@z3cka This PR now has two commits and can be squashed merged.

**Comment by z3cka** [comment]
deploying now

**Comment by z3cka** [comment]
`Copying of code from here to www-stage2.library.ucla.edu is complete.`

**Comment by z3cka** [comment]
`Copy of code from www-stage1.library.ucla.edu to  www-prod2.library.ucla.edu www-prod1.library.ucla.edu complete.`

**Pull request merged**
