### PR TITLE
#ready OP-809 fixes on correct field, removed from incorrect field ne…

### PR DESCRIPTION
**Pull request by emb03**
…ws highlights

@z3cka I am going to try to associate this PR with a milestone, so wish me luck

### CODE REVIEW

**Comment by z3cka** [comment]
deploying to `www-test`

**Comment by z3cka** [comment]
`Copying of code from here to www-test2.library.ucla.edu is complete.`

**Comment by z3cka** [comment]
reverting feature

**Comment by z3cka** [comment]
Title and 'more' links working! @emb03 nice.

**Comment by z3cka** [comment]
Behat test passed:
```
behat features/clean_news_highlights.feature 
Feature:
  In order to not see media codes on the /use page
  As a web visitor
  I need to not see theme

  Scenario: look for strange text on the /use page # features/clean_news_highlights.feature:6
    Given I am on "/use"                           # Behat\MinkExtension\Context\MinkContext::visit()
    Then I should not see "[["                     # Behat\MinkExtension\Context\MinkContext::assertPageNotContainsText()
    And the response should not contain "[["       # Behat\MinkExtension\Context\MinkContext::assertResponseNotContains()
    And I should see "more"                        # Behat\MinkExtension\Context\MinkContext::assertPageContainsText()
    When I follow "more"                           # Behat\MinkExtension\Context\MinkContext::clickLink()
    Then the response status code should be 200    # Behat\MinkExtension\Context\MinkContext::assertResponseStatus()
    Given I am on "/use"                           # Behat\MinkExtension\Context\MinkContext::visit()
    When I follow "Testing News"                   # Behat\MinkExtension\Context\MinkContext::clickLink()
    Then the response status code should be 200    # Behat\MinkExtension\Context\MinkContext::assertResponseStatus()

1 scenario (1 passed)
9 steps (9 passed)
0m3.013s
```

**Comment by emb03** [comment]
@z3cka yay! nice test! Once PR made, I will add to JIRA DRUP-828

**Pull request merged**
