### PR TITLE
DRUP-1076: #ready css changes only makes bookplates responsive on sma…

### PR DESCRIPTION
**Pull request by emb03**
…ll screens
@z3cka plz merge and copy to test, css changes only, thx!

### CODE REVIEW

**Comment by z3cka** [comment]
no, will take a look now

**Comment by z3cka** [comment]
deploying to test now

**Comment by emb03** [comment]
Merci Beaucoup

**Comment by z3cka** [comment]
```
3 files changed, 20 insertions(+)
. . .
Copying of code from here to www-test2.library.ucla.edu is complete.
```

**Comment by emb03** [comment]
@z3cka I am trying to cherry-pick this commit to go to staging, but it says the commit is empty. There is only 1 commit, no conflicts. Will talk more when you feel better.

**Comment by z3cka** [comment]
@emb03 this looks right. Notice 

> `Date: Mon Nov 21 13:10:35 2016 -0800`
> `3 files changed, 20 insertions(+)`

that's the cherry pick being applied and committed. There will be no working changes after a cherry pick. 

Just push your new branch _(`bookplates/responsive_css-cp`)_ to your fork and submit a new pull request to upstream staging.

**Pull request merged**
