### PR TITLE
DRUP-811: Deployment package for ArticlesPlus and other tabbed search changes.

### PR DESCRIPTION
**Pull request by akohler**
Upgrades ucla_tab_search and ucla_search to 7.x-1.5.
Requires one database update.

commit d4317458776dc5b16ad6b02fd70eafa458785621
Author: Andy Kohler <akohler@library.ucla.edu>
Date:   Thu Mar 24 09:36:06 2016 -0800

    DRUP-813: Remove beta from version numbers, ready for release

commit 5697ebd4d48e4f28ffe3caa55141796a6b117e59
Author: Andy Kohler <akohler@library.ucla.edu>
Date:   Mon Mar 21 21:31:42 2016 -0800

    Version 7.x-1.5-beta5 of ucla_search.
    Adds 3 columns for logging form elements not used on all tabs:
    * search code (UCLA Library Catalog index code)
    * search limit (Summon ArticlesPlus peer review limit)
    * search type (UCelinks/SFX/Catalog contains/startswith/exact)

    Requires database update, and possibly reversion of
    search_log_data view.

    commit 2a11089519680bf82e062f0cbb5ce2ba5efd5543
    Author: Andy Kohler <akohler@library.ucla.edu>
    Date:   Mon Mar 21 21:27:03 2016 -0800

        DRUP-873: Increment ucla_search version

    commit e2e084ddf562a17e26b2488facd57ecf55cfde27
    Author: Andy Kohler <akohler@library.ucla.edu>
    Date:   Mon Mar 21 21:14:46 2016 -0800

        DRUP-873: Add new database columns to views; change default sort to date descending

    commit 9e133aef4dcdf8d2ccc262f4a9fe4128ef117dd4
    Author: Andy Kohler <akohler@library.ucla.edu>
    Date:   Mon Mar 21 17:27:26 2016 -0800

        DRUP-873: Log relevant form elements to new database columns

    commit 057423c5ba364e0f6a17afb499f6b4cd4d1636fb
    Author: Andy Kohler <akohler@library.ucla.edu>
    Date:   Mon Mar 21 17:16:42 2016 -0800

        DRUP-873: Rename search_limits column to search_limit for consistency

    commit f3d101d93492d0bd3e56d2cae3d178f336d93bd1
    Author: Andy Kohler <akohler@library.ucla.edu>
    Date:   Mon Mar 21 16:55:28 2016 -0800

        DRUP-873: Add search_code and search_type columns to ucla_search_log schema

    commit 6e50c0b497353baed95d9a1fa5dc3115fd369c18
    Author: Andy Kohler <akohler@library.ucla.edu>
    Date:   Mon Mar 21 16:12:33 2016 -0800

        DRUP-873: Add search_limit column to ucla_search_log schema

commit f88bc7b97bc9d726b02c77187f33fdb809f8a795
Author: Andy Kohler <akohler@library.ucla.edu>
Date:   Mon Mar 21 10:49:22 2016 -0800

    Final (!?) UI changes for new ArticlesPlus tab

    commit db3e1b0fbc2213944bd9e372ef5422cf44bba176
    Author: Andy Kohler <akohler@library.ucla.edu>
    Date:   Mon Mar 21 10:48:58 2016 -0800

        DRUP-813: Increment module versions

    commit 503fa726a82591d1011d835535e6ccae6dde0bfb
    Author: Andy Kohler <akohler@library.ucla.edu>
    Date:   Mon Mar 21 10:41:41 2016 -0800

        DRUP-812: Add ArticlesPlus to search-log-data view, rename Articles to Articles (OLD)

    commit 938ded196298ba1a7020159c3108a0c300077caa
    Author: Andy Kohler <akohler@library.ucla.edu>
    Date:   Mon Mar 21 10:30:37 2016 -0800

        DRUP-816: Remove ArticlesPlus image and theme template, replace with text description

commit ba2a03846e015842d780ae558ae8aef3f649000c
Author: Andy Kohler <akohler@library.ucla.edu>
Date:   Fri Mar 18 14:18:05 2016 -0800

    DRUP-811: Fix problem with naive handling of text_query when back button is used

commit 166c5a53a0381bcf074c151470e2068bda6b0f40
Author: Andy Kohler <akohler@library.ucla.edu>
Date:   Thu Mar 17 22:46:36 2016 -0800

    DRUP-811: Fix form handler problem caused by url hash fragments

commit 339abe8a624a0977e1d9dea8a627775cff889119
Author: Casey Grzecka <cgrzecka@library.ucla.edu>
Date:   Mon Mar 14 18:26:03 2016 +0000

    DRUP-811: #ready adds static URLS for homepage search tab widget that highlight the desired tab
    Squashed commit of the following:

    commit 6c6f27bcb55e8c7902af38e90c650d29c393f7e7
    Author: Casey Grzecka <cgrzecka@library.ucla.edu>
    Date:   Mon Mar 14 18:21:02 2016 +0000

        adds a mouseup listener to the mousedowned object so that it is slightly less wonky, though still not perfect

    commit a8bec75ec75487bc434f18b7ff41938b86d32f07
    Merge: dcd49a6 afcd974
    Author: Casey Grzecka <cgrzecka@library.ucla.edu>
    Date:   Fri Mar 11 22:42:44 2016 +0000

        Merge branch 'search_url' of github.com:z3cka/libraryweb-site into search_url

    commit dcd49a6b36f0267a6a00d8068173eba202f23904
    Author: Casey Grzecka <cgrzecka@library.ucla.edu>
    Date:   Fri Mar 11 22:40:25 2016 +0000

        set the URL #hash based on the clicking of tabs

    commit aff341697bab63354761bced0c07fdff77eff5b7
    Author: Casey Grzecka <cgrzecka@library.ucla.edu>
    Date:   Wed Mar 9 19:05:46 2016 +0000

        DRUP-811: WIP on using hash-lander for home page search widget

    commit afcd9741e328469acbc3a45bc7f4722e936f8700
    Author: Casey Grzecka <cgrzecka@library.ucla.edu>
    Date:   Fri Mar 11 22:40:25 2016 +0000

        set the URL #hash based on the clicking of tabs

    commit 866d4daa7cdcfa486810174822b166971137439f
    Author: Casey Grzecka <cgrzecka@library.ucla.edu>
    Date:   Wed Mar 9 19:05:46 2016 +0000

        DRUP-811: WIP on using hash-lander for home page search widget

commit d9519b60b40c1900b82b5cabcd125db45d5e46b2
Author: Andy Kohler <akohler@library.ucla.edu>
Date:   Thu Mar 10 13:25:04 2016 -0900

    DRUP-858: Add accessibility labels to designated controls on tabbed search form

commit 2dd41b11c382cdb4a7182016e89d51b2ab4dfc98
Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
Date:   Wed Mar 9 08:25:22 2016 -0800

    DRUP-860: adds text-indent: 7px to tabbed search on homepage

commit fa74d7b55becdac85240b3fbb6629547ee382429
Author: Andy Kohler <akohler@library.ucla.edu>
Date:   Tue Mar 8 19:43:51 2016 -0900

    Version 7.x-1.5-beta3 of tabbed search.
    Squashed commits include:

    commit 7372e5e26a0ee69a71d8d8cda6e78593de55ca91
    Author: Andy Kohler <akohler@library.ucla.edu>
    Date:   Tue Mar 8 19:41:59 2016 -0900

        DRUP-813: Increase version to 7.x-1.5-beta3

    commit fb644214f4ada454a2c7cd831944fa277aa80235
    Author: Andy Kohler <akohler@library.ucla.edu>
    Date:   Tue Mar 8 18:42:25 2016 -0900

        DRUP-819: Make container names consistent, rename theme file to match

    commit 4e59adb46bb292cf0d9b855301b8ee4ed6d4faa7
    Author: Andy Kohler <akohler@library.ucla.edu>
    Date:   Tue Mar 8 18:33:13 2016 -0900

        DRUP-815: Remove search handler for old Articles tab

    commit 981acfbc99f84981a3c1db10d62f8a27fcea40b0
    Author: Andy Kohler <akohler@library.ucla.edu>
    Date:   Tue Mar 8 18:29:31 2016 -0900

        DRUP-815: Remove old Articles tab and form handler

    commit 513dbb8b5f0a61a88dda872e94cee50f3b3d3e47
    Author: Andy Kohler <akohler@library.ucla.edu>
    Date:   Tue Mar 8 15:31:21 2016 -0900

        DRUP-815: Change peer-reviewed wording again

commit f93a124816d7735f3b330acd34b1182f6c00308d
Author: Andy Kohler <akohler@library.ucla.edu>
Date:   Thu Mar 3 12:53:20 2016 -0900

    Version 7.x-1.5-beta2 of tabbed search.
    Squashed commits include (redundant merge commits not listed):

    commit 752412d747cd717d238ce28aba35dbb7bc51a8c2
    Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
    Date:   Thu Mar 3 10:56:32 2016 -0800

        DRUP-819: adds scss file for homepage css to resize AP graphic, optimizes SVG code in template file

    commit bbd8fb6ebb65020cc77820b7337ad6cd9daff5cd
    Author: Casey Grzecka <cgrzecka@library.ucla.edu>
    Date:   Thu Mar 3 21:12:31 2016 +0000

        fixes undefined index 'render element' php notice that Andy found

    commit 7997af508f6ff4726a3d0f71d43b48405cd216b0
    Author: Casey Grzecka <cgrzecka@library.ucla.edu>
    Date:   Thu Mar 3 05:58:23 2016 +0000

        adds svg image to search widget via #theme; requires a bit more css work

    commit 287e68ca3961eb5af99d2cf88a13092514161cf7
    Author: Andy Kohler <akohler@library.ucla.edu>
    Date:   Wed Mar 2 10:43:22 2016 -0900

        DRUP-815: Change wording of peer-review limit

    commit 2883289a74ab12904d0d6faed1376bf754d9bc28
    Author: Andy Kohler <akohler@library.ucla.edu>
    Date:   Wed Mar 2 10:42:30 2016 -0900

        DRUP-812: Removed errant debugging comment

    commit 482c6594e402e7473772f89bdb0350010eccb4eb
    Author: Andy Kohler <akohler@library.ucla.edu>
    Date:   Wed Mar 2 10:31:32 2016 -0900

        DRUP-813: Deleted empty README.md file

commit c99301cb3fba692ba39c95d51565c60a5edd06cb
Author: Andy Kohler <akohler@library.ucla.edu>
Date:   Wed Feb 24 14:18:47 2016 -0900

    Squashed commit for version 7.x-1.5-alpha1 of ucla_tab_search and ucla_search modules.
    This adds an ArticlesPlus tab to the homepage search form.

    commit 9f471f6b978478dfe8b0a89eccd5c8a4beb6b469
    Author: Andy Kohler <akohler@library.ucla.edu>
    Date:   Wed Feb 24 14:15:50 2016 -0900

        DRUP-815: Add description text and placeholder image for ArticlesPlus tab

    commit 8290fe4e10ad40b0c40039fd1bc7549ede6d066f
    Author: Andy Kohler <akohler@library.ucla.edu>
    Date:   Wed Feb 24 13:41:09 2016 -0900

        DRUP-817: Fix peer review limit to work correctly

    commit a78fe41cc6a1e49ca6496d7ad5886b8bfc6e0c44
    Author: Andy Kohler <akohler@library.ucla.edu>
    Date:   Wed Feb 24 12:39:48 2016 -0900

        DRUP-813: Increment version to 7.x-1.5-alpha1

    commit f669849589a0236bdd419621110ce2fbbaf28a18
    Author: Andy Kohler <akohler@library.ucla.edu>
    Date:   Wed Feb 24 12:36:30 2016 -0900

        DRUP-815: Add search handler for ArticlesPlus

    commit acf3e177ee63d308e5c53f79be2e6fbcf2b72274
    Author: Andy Kohler <akohler@library.ucla.edu>
    Date:   Wed Feb 24 12:28:59 2016 -0900

        DRUP-815: Add basic mapping of ArticlesPlus search form to values for search/log handlers

    commit 0c134ced5c28f2304e38010fa00582bd1887961f
    Author: Andy Kohler <akohler@library.ucla.edu>
    Date:   Wed Feb 24 10:46:26 2016 -0900

        DRUP-817: Add checkbox for peer review limit

    commit 9ad20c1ef64ead96b45c0f7241edc44c9ac60e03
    Author: Andy Kohler <akohler@library.ucla.edu>
    Date:   Wed Feb 24 10:29:56 2016 -0900

        DRUP-816: Add Advanced Search link, though not opening in new tab

    commit aa405795f1bac20c7875a780e275c76d1f2e9af2
    Author: Andy Kohler <akohler@library.ucla.edu>
    Date:   Wed Feb 24 10:22:54 2016 -0900

        DRUP-815: Add Search button to ArticlesPlus tab

    commit b27e097b9c042f7f2daf2969db758d57438110ff
    Author: Andy Kohler <akohler@library.ucla.edu>
    Date:   Wed Feb 24 10:17:17 2016 -0900

        DRUP-815: Add ArticlesPlus to tabbed search, with basic search box

### CODE REVIEW

**Comment by z3cka** [comment]
Nice! look at that summary of commits!

**Comment by akohler** [comment]
@z3cka Here is the staging/deployment PR for ArticlesPlus etc.  It contains the (squashed) commits from all 11 ArticlesPlus 7.x-1.5 PRs (10 closed, one still open).

This does include the theme CSS changes made by @emb03 to support the ArticlesPlus image, which ultimately was not used.  I decided it was OK to leave those in rather than try to undo them, as the `.ap_graphic` bit won't hurt anything... hope this is OK.

**Comment by z3cka** [comment]
Ya, I think that's okay... we may want to clean it up on the next theme update... In the next PR coming to master I've upped the these version to 1.2 so we can hit this in 1.3

**Comment by akohler** [comment]
> In the next PR coming to master I've upped the these version to 1.2 so we can hit this in 1.3 
@z3cka You're referring to our theme version?

**Comment by z3cka** [comment]
> @z3cka You're referring to our theme version?
@akohler yes.

**Pull request merged**
