### PR TITLE
DRUP-657: squashed all blog related commits so far.

### PR DESCRIPTION
**Pull request by z3cka**
@akohler, @emb03 is going to pull this to her local and work from it. This is sort of a QA in dev. Please do not merge this request until we have QA'ed in our local.

Thanks!

DRUP-657: #comment formats archives links to match Wordpress
... does this by adding views logic to dynamically set exception handlers on handlers on contextual filters
 * TODO: figure out path alias strategy now that the views paths work like WP

DRUP-657: adds categories to the blog panel that was added as well TODO: remove dupes before views render

DRUP-657: Adds tags to blog sidebar

DRUP-657: Adds blog content view for showing the actual blog posts in the main content area

DRUP-657: adds blog_archives view TODO: needs output of links modifications and dynamic date exceptions

DRUP-657: adds categories to the blog panel that was added as well TODO: remove dupes before views render

DRUP-657: Adds blog content view for showing the actual blog posts in the main content area

DRUP-657: adds blog_archives view TODO: needs output of links modifications and dynamic date exceptions

### CODE REVIEW

**Comment by z3cka** [comment]
Just added some de-dupe functionality that may need some re-factoring. @akohler, what do you think about what I did in hook_views_pre_render() (here)[https://github.com/z3cka/libraryweb-site/blob/DRUP-657cp/www/sites/all/modules/features/uclalib_news/uclalib_news.module#L40]? Should I use a switch or something for this? I can walk you through the logic tomorrow.

**Comment by akohler** [comment]
@z3cka : I don't think a switch here is better than your if statements.  However, if I read this right, you are unsetting the "uniques" variable after going to the trouble of putting things into it, and I don't understand why.  If this is intended, a comment before "unset($uniques)" would be helpful.  If nuking $uniques is not intended, maybe I'm misunderstanding this code.

**Comment by z3cka** [comment]
@akohler I was thinking I needed to unset the array in case the pane gets rendered more than once on the page; but since the $uniques array gets re-initialized on line [43](https://github.com/z3cka/libraryweb-site/blob/DRUP-657cp/www/sites/all/modules/features/uclalib_news/uclalib_news.module#L43) each time this hook gets fired, there is no need to unset it. removed in 2396a99.

**Comment by z3cka** [comment]
okay @emb03 —see if this fixes those archive links for you again.

**Comment by z3cka** [comment]
closing in favor of a cleaner, rebased and squashed – #90

**Pull request closed without merging**
