### PR TITLE
OP-871: #ready css delete css that was not being used

### PR DESCRIPTION
**Pull request by emb03**
@z3cka will make a deploy ticket for this...

### CODE REVIEW

**Comment by z3cka** [comment]
@emb03 is this supposed to go the `UCLALibrary:master` first? your hash says #ready, but you target is `UCLALibrary:staging`

**Comment by emb03** [comment]
@z3cka it already went to test.

**Comment by z3cka** [comment]
Great! ... next time use `#awaiting` will merge now

**Comment by emb03** [comment]
K will do

**Comment by z3cka** [comment]
this will be deployed at next deployment.

**Comment by z3cka** [comment]
```
[druadmin@lit210v www]$ git pull
remote: Counting objects: 14, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 14 (delta 4), reused 4 (delta 4), pack-reused 0
Unpacking objects: 100% (14/14), done.
From https://github.com/UCLALibrary/libraryweb-site
   9668a5a..f8932b5  staging    -> origin/staging
Updating 9668a5a..f8932b5
Fast-forward
 www/sites/all/themes/uclalib_omega/css/uclalib-omega.no-query.css      | 5 -----
 www/sites/all/themes/uclalib_omega/css/uclalib-omega.styles.css        | 5 -----
 www/sites/all/themes/uclalib_omega/sass/components/_staff_profile.scss | 5 -----
 3 files changed, 15 deletions(-)
```
`Copying Drupal code files from www-stage1.library.ucla.edu to www-prod2.library.ucla.edu`

**Comment by z3cka** [comment]
`Copy of code from www-stage1.library.ucla.edu to  www-prod2.library.ucla.edu www-prod1.library.ucla.edu complete.`

**Pull request merged**
