### PR TITLE
DRUP-895: #verified Adds bookplates functionality to site

### PR DESCRIPTION
**Pull request by emb03**
commit 853ff9b39dcdda7be7577886bf0adbf302c30257
Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
Date:   Thu Jul 14 08:44:47 2016 -0700

    DRUP-895: #ready converts css to sass, ups version number

commit bf98d9e34c9869214c9d26bbbc07671d70a9cfc1
Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
Date:   Wed Jul 13 17:38:58 2016 -0700

    DRUP-895: #ready fixes type "make" should be "made" in view

commit 9f61ba9841c561b3145e19f86a69d04510dbb195
Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
Date:   Wed Jul 13 12:02:23 2016 -0700

    DRUP 896: #ready updates pm a-z list, update taxonomy view, fixes typo, css, reset menu item to 0

commit 995182a33a9b0bbdcc235c21f5ec4a16ae98138b
Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
Date:   Tue Jul 12 08:42:24 2016 -0700

    DRUP-896: #ready Adds missing page manager to Bookplates donor directory

commit 17817fe85f4d2717e98d7e564fb822b3918d7980
Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
Date:   Mon Jul 11 16:21:24 2016 -0700

    DRUP-896: #ready adds donor directory to Bookplates

commit d4027d1278a7633082380ac2426181a69f9148ea
Author: Casey Grzecka <cgrzecka@library.ucla.edu>
Date:   Thu Jul 7 23:56:42 2016 +0000

    DRUP-911: #ready adds breadcrumbs, menu, refines search results view, css for donor names

    commit b28dd6e6031cf594422730955049353ee93cb066
    Author: Casey Grzecka <cgrzecka@library.ucla.edu>
    Date:   Thu Jul 7 22:09:24 2016 +0000

        DRUP-911: makes bookplate content type's default menu match the new sans breadcrumb name

    commit 0c0a5ad19992719eae679504b5209c34064d1bda
    Author: Casey Grzecka <cgrzecka@library.ucla.edu>
    Date:   Thu Jul 7 21:35:42 2016 +0000

        DRUP-911: removes 'breadcrumb' from menu title et al

    commit 3d1727f4dae3c82749224501187f6fdcc0b4b3ae
    Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
    Date:   Wed Jul 6 12:49:25 2016 -0700

        DRUP-911: #ready adds breadcrumbs, menu, refines search results view, css for donor names

commit b13777e75b5ee6a5c2b297c2ff29cd519aeddfa3
Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
Date:   Tue Jun 21 08:30:23 2016 -0700

    DRUP-895: #ready squashed commits
    prevents search box placeholder text from leaking out of bookplates
    clean up in prep for breadcrumbs
    updates css based on path alias
    updates info version #

commit 0c09ffb46b34f113301c75e9803f672dde98a4b1
Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
Date:   Tue May 24 11:29:19 2016 -0700

    Drup-895: detailed commit messages in PR

commit 2071d841790819c630ec364b8bdccd6c7b9e66c1
Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
Date:   Mon May 23 13:08:43 2016 -0700

    DRUP895: fixes omg cropping and dupes on taxonomy results page, fixed undefined variable "donor_names", updates version info

commit 067a88d58f095a3dd73e7fd871335df7b6791ef0
Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
Date:   Thu May 19 10:00:57 2016 -0700

    Changes to subject area views

    commit bdd5acfb26f0054e538a1af282b085275bd5a57b
    Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
    Date:   Thu May 19 09:56:42 2016 -0700

        adds css for taxonomy section to match landing page, changes pagination, new version number

    commit 18cdd9a1dad7ac4414e0062894e748138ba6f626
    Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
    Date:   Thu May 19 08:23:21 2016 -0700

        removes custom templates and reverts to using default templates

commit 18bdc006209903d6f77730b862ad7bd097ecfcd4
Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
Date:   Wed May 18 16:33:47 2016 -0700

    DRUP-895: #ready fixes formatting in .tpl, code styles clean-up, removes custom code from theme.inc

    commit 6a080bcdaf7e02d2244c563d68a081dab04e79fa
    Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
    Date:   Wed May 18 15:16:31 2016 -0700

        DRUP-895 #ready removes contrib hack in theme.inc, cleans up formatting

    commit 6252b8be414e5d1975cd3d22f25c6ee731577f16
    Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
    Date:   Wed May 18 14:41:49 2016 -0700

        Squashed commit of the following:

        commit 1ee932bebd1fc37633bccbe2b9744e74daa35df0
        Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
        Date:   Wed May 18 14:37:52 2016 -0700

            DRUP-895: #ready removes fields, removes unnecessary function, updates version info

        commit 7e86f1b96a11e634b8d24b3659b0f45df2699299
        Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
        Date:   Wed May 18 13:23:48 2016 -0700

            Squashed commit of the following:

            commit 0ff5854b8941d59cdc993f04ec752b85a1e62621
            Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
            Date:   Wed May 18 10:12:57 2016 -0700

                fixes donor name display on subject area taxonomy pages

            commit 3c4aba2f6ff425b3d29de6aaf4ea5468b898a783
            Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
            Date:   Wed May 18 09:52:14 2016 -0700

                removed line: current_display != 'bookplates_landing_page' because this may interfere with subject area (taxonomy) display of donor names

            commit 1fef59427e1f4a3ff66c746af6ccec8c4689c023
            Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
            Date:   Wed May 18 09:09:09 2016 -0700

                css fixes, taxonomy (subject areas) view

            commit 1124dcb3dc53953f57ab4c05acf7e73fae0cfc7f
            Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
            Date:   Wed May 18 08:40:48 2016 -0700

                fixes fixed height of images on landing page, css

            commit c4087261b1ac3d22b2ca86c5576cdd3b94dcd57d
            Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
            Date:   Tue May 17 13:45:19 2016 -0700

                fixes donor field name collection, other minor fixes

            commit 55179daaea64e339498c4a7731b136fa79c9e6ed
            Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
            Date:   Fri May 6 15:14:04 2016 -0700

                added donor first name last field to related fields in search api

            commit cd1a41b587c80e867e7d490afa391aa32a5855a0
            Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
            Date:   Fri May 6 15:03:30 2016 -0700

                added field collection donor to views bookplate search

            commit e03db72fcb09186f63fc4684b2992517329a37b8
            Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
            Date:   Fri May 6 14:53:29 2016 -0700

                added field collections to search api

            commit 7669fa2f56b9bd5a6a316c29e4f38fd3ef48ed54
            Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
            Date:   Fri May 6 14:20:39 2016 -0700

                fixing field collection output for single donor

            commit f36d7716c2993ea1e5f40b9376b6190e8e9f5141
            Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
            Date:   Fri May 6 12:41:53 2016 -0700

                field collections view views field template changes, changes to single node view

            commit 7044e50813c792314a1e168b7dc4ef98b376ea2e
            Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
            Date:   Fri May 6 12:41:17 2016 -0700

                field collections pop and implode array try #1

            commit 750f8b01c2c35d9b309cd39b3d6985939cf97257
            Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
            Date:   Fri Apr 8 08:30:34 2016 -0700

                DRUP-895: removes field instance and field base for 'sort by' field, to be replaced by functionality of 'donor name field collection'

            commit bbbcf9dec6b999a7b02a6b3ebe1f5a2d9a6cfdb2
            Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
            Date:   Fri Apr 8 08:21:21 2016 -0700

                DRUP-885: incorporates Casey's work on field collection names

            commit c00b0b3dd48d3c376574cd8683ab4844def8dedb
            Merge: c9e661f 8fe3bf6
            Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
            Date:   Tue Apr 5 14:29:19 2016 -0700

                Merge branch 'bookplates_donor-field-collection' of https://github.com/z3cka/libraryweb-site into bookplates/qa_round_3
                Merging Casey's work on adding donor names as field collections

            commit 8fe3bf6bbf7b01e52c2681543aaee3042db4e8f5
            Author: Casey Grzecka <cgrzecka@library.ucla.edu>
            Date:   Thu Mar 31 12:38:18 2016 -0700

                DRUP-885: adds donor names as field collection. also removes unused field groups

commit f6edbc5f94d0d89cf661ae2d2a9c156557c06435
Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
Date:   Thu Mar 10 14:02:06 2016 -0800

    DRUP-802: replaces 'access arguments' with correct value

commit 0a8d5269e06e1cf082442929c53a0b53fa3e8e9b
Author: Casey Grzecka <cgrzecka@library.ucla.edu>
Date:   Wed Mar 9 20:09:11 2016 +0000

    Squashed commit of the following:

    commit b2e6c36fa68b7288a60f387f8cb9d1111677097e
    Author: Casey Grzecka <cgrzecka@library.ucla.edu>
    Date:   Wed Mar 9 19:58:00 2016 +0000

        removes uneeded template and removes debug statement from other template

    commit a2c50146cfb50f0e513ef6a0cfe8607f718064a2
    Author: Casey Grzecka <cgrzecka@library.ucla.edu>
    Date:   Wed Mar 9 19:53:35 2016 +0000

        manually removes broken field handlers from views tracked by features

    commit 910f4ec0ee51e5fc8b085e14e091a32cf7c110fc
    Author: Casey Grzecka <cgrzecka@library.ucla.edu>
    Date:   Wed Mar 2 23:58:08 2016 +0000

        adds conditional for field in certain view and modifies field label on bookplates landing

    commit acbc0d7b15c33195ba9eea545bfdf4922074a13a
    Author: Casey Grzecka <cgrzecka@library.ucla.edu>
    Date:   Wed Mar 2 19:59:55 2016 +0000

        removes 'and' seperator for single donor in field display

    commit e02ee94562e858972d5387b454b15339056e4776
    Author: Casey Grzecka <cgrzecka@library.ucla.edu>
    Date:   Wed Mar 2 19:03:19 2016 +0000

        makes field_donor_name_bookplates field's Display type an unordered list and removes the simple seperator ' and ' string

    commit a52da0ea432df86b80f5520c926f391591763616
    Author: Casey Grzecka <cgrzecka@library.ucla.edu>
    Date:   Wed Mar 2 18:22:15 2016 +0000

        appends the last donor with an 'and' before it

    commit f1806809afaf3f63eadf5992773a4c699b32ff1c
    Author: Casey Grzecka <cgrzecka@library.ucla.edu>
    Date:   Wed Mar 2 01:17:07 2016 +0000

        WIP on adding commas between the donors. TODO: insert 'and' before the last donor sans oxford comma

    commit cbba53e4eeaa7c060ef989655c63dd226661e4c3
    Author: Casey Grzecka <cgrzecka@library.ucla.edu>
    Date:   Tue Mar 1 23:34:51 2016 +0000

        adds conditional that hides uclalib_bookplates_spak_args field when empty

    commit ab29ebe551de2de763df1433878c270d9473be32
    Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
    Date:   Fri Feb 26 12:46:59 2016 -0800

        DRUP-802: #ready adds view for term variant

    commit 4074873edaa2270a11572fce1b766b688245be3e
    Author: Casey Grzecka <cgrzecka@library.ucla.edu>
    Date:   Wed Feb 24 20:11:24 2016 +0000

        adds target attribute to field_bookplates_spak_code field preprocessor to open link in a new browser window

    commit b870b6af5aeff2b6779a9e382182ccabe554eb71
    Author: Casey Grzecka <cgrzecka@library.ucla.edu>
    Date:   Wed Feb 24 19:31:47 2016 +0000

        removes rewrite results in field handler for field_bookplates_spak_code in views

    commit 23f19141883347894701c02af508cf3578b7002c
    Author: Casey Grzecka <cgrzecka@library.ucla.edu>
    Date:   Wed Feb 24 19:16:29 2016 +0000

        removes broken handler from bookplates view

    commit ba10542dda2c5bff42c75ccc6ff2cf2f09cba1f9
    Author: Casey Grzecka <cgrzecka@library.ucla.edu>
    Date:   Wed Feb 24 19:08:16 2016 +0000

        removes fields that were deployed to www-test and are no longer needed

    commit cd0697a095cbea2dc2f39029e21813f77aa75f60
    Author: Casey Grzecka <cgrzecka@library.ucla.edu>
    Date:   Wed Feb 24 17:58:11 2016 +0000

        adds preprocessor for field_bookplates_spak_code URL and some cole cleanup

    commit fa4547fd2da3969c439d2391a3be0f69d9763481
    Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
    Date:   Mon Feb 22 09:11:55 2016 -0800

        Squashed commit of the following:

        commit c1dc3c98635bb2af7e8bd81e8d0891ed79a481a8
        Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
        Date:   Mon Feb 22 09:04:50 2016 -0800

            removes field_permssions module

        commit 3ffcb32e2f322740730d003d338f62d97baee09f
        Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
        Date:   Mon Feb 22 08:53:21 2016 -0800

            removing conflict markup

        commit f84b896cbfedb3cea75552aca2368fcb9b47da22
        Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
        Date:   Tue Feb 16 14:02:41 2016 -0800

            adds bookplate admin form and fixes conflict

            Conflicts:
            	www/sites/all/modules/features/uclalib_bookplates/uclalib_bookplates.module

        commit c1fc222a58e4e6297ce4551677bf4e02bb6398b0
        Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
        Date:   Fri Feb 19 15:20:32 2016 -0800

            #ready DRUP-802: deleted spak code before after fields

        commit 0e99b80aadd5a507e5c6f5c57b4e429d6ad52dba
        Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
        Date:   Tue Feb 16 08:18:10 2016 -0800

            #ready DRUP-802: all changes here: http://ucla.in/1QjFJMy

commit dfc641ecfe0484e027eea3404241c45f1f89b033
Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
Date:   Wed Jan 6 11:06:00 2016 -0800

    removes 'administer panelizer node bookplates' permissions reference from '...features.user_permission.inc

commit b7da27e645a5ffb6974ca771ee93526a96a94e33
Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
Date:   Wed Jan 6 10:56:09 2016 -0800

    changed .info version to beta4

commit ae464254abc88b04828174ab5fc746ea86d5bd98
Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
Date:   Wed Jan 6 10:53:29 2016 -0800

    fe_block facet api references to overcome false override for good this times

commit 8bfe59f13d778a8e00530621a6eb7fbfc0de39f2
Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
Date:   Wed Jan 6 10:42:07 2016 -0800

    removes panelizer and fe_block facet api references to overcome false overrides

commit 4e0d0d16c1c1c0ca7a1d64231fd02a1c04424a33
Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
Date:   Wed Jan 6 08:06:15 2016 -0800

    DRUP-802 adds author and donor name to search index

commit 46179ee5b563260f4132cb92787bbf849b7878de
Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
Date:   Wed Jan 6 08:32:35 2016 -0800

    DRUP-802: adds new versioning beta2

commit 2f39b52fdde7c9e0c843c134bf2c60991a631ec1
Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
Date:   Tue Jan 5 10:57:44 2016 -0800

    DRUP-802 #ready adds bookplates module

### CODE REVIEW

**Comment by emb03** [comment]
@z3cka Gary still hasn't approved this for deployment. Don't do anything until you see a Jira deployment ticket from me. Thanks, this was awesome!

**Comment by z3cka** [comment]
Okay. I was just checking in. I should be available on Sat. night to deploy if needed. I'm out for the rest of today, but I will monitor email for that Jira issue.

**Comment by emb03** [comment]
@z3cka Thanks, you're the best! Have a good day off!

**Comment by z3cka** [comment]
`Copy of code from www-stage1.library.ucla.edu to  www-prod2.library.ucla.edu www-prod1.library.ucla.edu complete.`

Bookplates are ready for content in production. Once menu items have been created, we will have to set the default parent menu item on the bookplates content type. This will cause the bookplates feature to become overridden. We will then re-roll _(feature update)_ the feature and prep it for the next deployment.

**Pull request merged**
