### PR TITLE
DRUP-1043: #ready adds mobile css and menu title

### PR DESCRIPTION
**Pull request by emb03**
@z3cka please merge to stage, fixes bookplates features on prod 'overridden' state

### CODE REVIEW

**Comment by emb03** [comment]
@z3cka is that another PR to master?

**Comment by z3cka** [comment]
yes

**Comment by emb03** [comment]
@z3cka Do I have to wait for you to close the PR before submitting to master?

**Comment by z3cka** [comment]
no, you can apply this same commit to master

**Comment by z3cka** [comment]
`Copying of code from here to www-stage2.library.ucla.edu is complete.`

**Pull request merged**
