### PR TITLE
DRUP-1061: #awaiting removes hyphen, replace with pipe, make time boldface

### PR DESCRIPTION
**Pull request by emb03**
@z3cka I will make a deploy ticket, this was approved on www-test

### CODE REVIEW

**Comment by z3cka** [comment]
@emb03 why was this PR closed?

**Comment by emb03** [comment]
@z3cka I don't know! it has two commits, I need to cherry-pick?

**Comment by z3cka** [comment]
@emb03 it says you closed it, that's why I asked. :-) No cherry pick needed; could have been squash merged. We can reopen and queue for the deployment if you'd like.

**Comment by emb03** [comment]
@z3cka yea, I did close it, but I have no idea why. 🎱

**Comment by z3cka** [comment]
hmmm, strange. I just wanted to make sure to ask you before reopening. Please make a deployment ticket and add label and it will go this weekend.

**Comment by z3cka** [comment]
`Copy of code from www-stage1.library.ucla.edu to  www-prod2.library.ucla.edu www-prod1.library.ucla.edu complete.`

**Pull request merged**
