### PR TITLE
Homepage/search widget

### PR DESCRIPTION
**Pull request by emb03**
@z3cka have to resolve conflicts

### CODE REVIEW

**Comment by emb03** [comment]
@z3cka I have tried to cherry-pick this three times and it's not working. Not sure what I am doing wrong.

**Comment by z3cka** [comment]
PRs to upstream:master require rebasing from upstream... not sure why a cherry pick would be needed.

**Comment by z3cka** [comment]
...or just fix the conflicts

**Comment by z3cka** [comment]
replaced by #359

**Pull request closed without merging**
