### PR TITLE
DRUP-895: #ready prevents search box placeholder text from leaking out of bookplates

### PR DESCRIPTION
**Pull request by emb03**
prevents search box placeholder text from leaking out of bookplates
cleanup in prep for breadcrumbs
updates css based on path alias
updates info version #
adds new menu bookplates breadcrumbs
updated page manager -- specific endowment title is now title instead of generic "Collections Endowment"

### CODE REVIEW

**Comment by emb03** [comment]
@z3cka plz merge to test and see what we get :)

**Comment by z3cka** [comment]
this PR could use a better title befor it gets merged

**Comment by z3cka** [comment]
everything else looks good, will deploy after rename of PR... I think you can just edit it

**Comment by z3cka** [comment]
`Copying of code from here to www-test2.library.ucla.edu is complete.`

**Pull request merged**
