### PR TITLE
WS-960l - added code for Drupal log out; layout change

### PR DESCRIPTION
**Pull request by darrowcoucla**
Added code to completely log out Drupal user
Minor formatting on the web page

### CODE REVIEW

**Comment by darrowcoucla** [comment]
I made another commit for WS-960l - can I add this new commit to this existing PR (#443)? The commit is:
5c2ea6fa1dd09c9adb20158ae8b927eb9cebf15d

thks!

**Comment by darrowcoucla** [comment]
And, one more commit for expanded touch response area for tablet usage.

**Comment by z3cka** [comment]
deploying to `www-test` now along with #442.

**Comment by z3cka** [comment]
`Copying of code from here to www-test2.library.ucla.edu is complete.`

**Pull request merged**
