### PR TITLE
DRUP-1127: #ready adds missing labels to search forms on /contact , /bookplates and /staff

### PR DESCRIPTION
**Pull request by z3cka**
also fises DRUP-1141

Squashed commit of the following:

commit 1bf044dacdab5619f5bb6b76e3c9aef95a49d1a7
Author: Casey Grzecka <cgrzecka@library.ucla.edu>
Date:   Thu Feb 2 01:59:54 2017 +0000

    DRUP-1127: adds labels to staff search box on /staff TODO: sass needs re-compiling

commit eedff9366ba83efa4c011c090717ca936045c7e7
Author: Casey Grzecka <cgrzecka@library.ucla.edu>
Date:   Tue Jan 31 16:54:30 2017 +0000

    DRUP-1127: adds <label> text to /bookplayes sidebar search and hides it

commit 718d8f3f1cd9c9b3c3eda3a28d40fa0cff53273c
Author: Casey Grzecka <cgrzecka@library.ucla.edu>
Date:   Fri Jan 27 01:24:40 2017 +0000

    bug fix; fixes php error: undefined index field_donor_name_first

    Conflicts:
    	www/sites/all/modules/features/uclalib_bookplates/uclalib_bookplates.info

commit 4cf02ebc4be4c1f9feeffc1548bd8aa03378049a
Author: Casey Grzecka <cgrzecka@library.ucla.edu>
Date:   Fri Jan 27 00:37:40 2017 +0000

    DRUP-1127: moves inline template to its own file for /contact

commit aec87d1cbcfff5f0436c7609719b5584ef29c03d
Author: Casey Grzecka <cgrzecka@library.ucla.edu>
Date:   Thu Jan 26 21:29:56 2017 +0000

    DRUP-1127: adds label to /contact TODO: move inline template to own file

### CODE REVIEW

**Comment by z3cka** [comment]
@emb03 please compile this scss change for me. I'll help you with the git steps if needed.

**Comment by emb03** [comment]
Sure thing, I have one more css change to make too. I will need a quick recap of what to do. Can I just track your branch, pull it down (do I need to make a new branch or can I use your branch?), make changes and then push to my branch. No need to make a PR, right?

**Comment by z3cka** [comment]
`Copying of code from here to www-test2.library.ucla.edu is complete.`

**Comment by z3cka** [comment]
`Copying of code from here to www-test2.library.ucla.edu is complete.`

**Pull request merged**
