### PR TITLE
Updates Drupal core to 7.58

### PR DESCRIPTION
**Pull request by z3cka**
This includes fixes for two major security releases:
* SA-CORE-2018-001
* SA-CORE-2018-002

@akohler and @darrowco-ucla please take a look, I'd like to roll this out ASAP.

### CODE REVIEW

**Comment by z3cka** [comment]
We do some strange stuff with `robots.txt` so I will add those modifications now.

**Comment by akohler** [comment]
250+ changed files?  Sure, looks fine to me 👍 Many of the changes are to Drupal internals and would take a long time to evaluate.  Given the critical nature... make sure we have backups, then go for it.

**Comment by z3cka** [comment]
Cool. Yes, most of this is for 7.57.... for the highly critical update see: 93007259e0ecbf2666631e47d5947322819abced

**Comment by z3cka** [comment]
here we go! _to `www-test`!_

**Comment by akohler** [comment]
Commented in Slack but I'll repeat here: `request-sanitizer` uses a whitelist but I don't see anything in the 7.58 commit defining the contents of that whitelist.

**Comment by z3cka** [comment]
ya. not sure... is on test now `Copying of code from here to www-test2.library.ucla.edu is complete.`

**Pull request merged**
