### PR TITLE
OP-882 #awaiting fixes keyword dropdown with css

### PR DESCRIPTION
**Pull request by emb03**
@z3cka this is ready to go to stage

### CODE REVIEW

**Comment by emb03** [comment]
@z3cka awesome sauce

**Comment by z3cka** [comment]
preparing to stage now

**Comment by z3cka** [comment]
```
3 files changed, 68 insertions(+), 40 deletions(-)
. . .
Copying of code from here to www-stage2.library.ucla.edu is complete.
```

**Comment by z3cka** [comment]
`Copy of code from www-stage1.library.ucla.edu to  www-prod2.library.ucla.edu www-prod1.library.ucla.edu complete.`

**Pull request merged**
