### PR TITLE
DRUP-798: fixes missing selection rules in staff profile node template

### PR DESCRIPTION
**Pull request by emb03**
commit 2074a8fa8f9ce4215a139b95382909c456fa046b
Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
Date:   Tue Dec 8 16:03:23 2015 -0800

    update version number (no ticket)

commit 9c7ca1d22d81c7779146a7bcf86c1282ce375300
Author: Elaine Blakeman <elaineblakeman@library.ucla.edu>
Date:   Thu Dec 3 16:57:01 2015 -0800

    fixes missing selection rules in staff profile node template

### CODE REVIEW

**Comment by emb03** [comment]
@z3cka plz merge to test, we decided to leave hierarchies set to 0, thx

**Comment by z3cka** [comment]
deploying now

**Comment by z3cka** [comment]
`Copying of code from here to www-test2.library.ucla.edu is complete.`

**Comment by z3cka** [comment]
we now need to revert on `www-test`.

**Pull request merged**
