### PR TITLE
Drup 779 revisions test pr148 css quick links tidied up code

### PR DESCRIPTION
**Pull request by emb03**
@z3cka Hoping this landed in the right bucket. Plz test. thank you!

### CODE REVIEW

**Comment by z3cka** [comment]
well, you didn't have to create another PR as you could have pushed your latest commit to `emb03:revisions_testPR147_staff_profile` ... but this will do... closing #148.

**Comment by z3cka** [comment]
@emb03 please add [this branch](https://github.com/z3cka/libraryweb-site/tree/testPR149) to this PR. It includes the pathauto config for the Staff Profiles. Also, add anything that you saw that was missing.

I will continue with the left menu modifications.

**Comment by z3cka** [comment]
okay [testPR149](https://github.com/z3cka/libraryweb-site/tree/testPR149) has the latest... rebase commits and add CSS.

**Comment by z3cka** [comment]
@emb03 [testPR149](https://github.com/z3cka/libraryweb-site/tree/testPR149) now contains a better bean for the menu via [2da06ffd262de8f3037c32b6525154e94fe5e7b5](https://github.com/z3cka/libraryweb-site/commit/2da06ffd262de8f3037c32b6525154e94fe5e7b5)

So, you can rebase that into your next push or we can do it on the squash.

**Comment by z3cka** [comment]
@emb03 and another from [testPR149](https://github.com/z3cka/libraryweb-site/tree/testPR149)

**Comment by emb03** [comment]
@z3cka rebased and pushed back at ya!

**Comment by z3cka** [comment]
@emb03 one more time before we squash! 1877989 (on same branch as above).

**Comment by z3cka** [comment]
time to squash!

**Comment by z3cka** [comment]
nope. it's poor-man's-rebase(squash) time

**Pull request closed without merging**
