### PR TITLE
fe_block facet api references to overcome false override for good thi…

### PR DESCRIPTION
**Pull request by emb03**
… overrides
@z3cka merge to test, plz, thks

### CODE REVIEW

**Comment by z3cka** [comment]
@emb03 please up to beta4

**Comment by z3cka** [comment]
deploying to test

**Comment by z3cka** [comment]
looks good, please also remove the permissions array

**Comment by emb03** [comment]
@z3cka Do I need to do this still?

**Comment by z3cka** [comment]
this was done in: https://github.com/UCLALibrary/libraryweb-site/pull/179

**Pull request merged**
