### PR TITLE
DRUP-1002: #ready fixes give now button wrapping on small screens for…

### PR DESCRIPTION
**Pull request by emb03**
… logged in users
@z3cka changed padding and seems to fix wrapping issue with give now button, plz merge. Thx!

### CODE REVIEW

**Comment by z3cka** [comment]
Deploying to `www-test` now.

**Comment by z3cka** [comment]
`Copying of code from here to www-test2.library.ucla.edu is complete.`

**Comment by emb03** [comment]
@Thanks! changing padding from 20px to 15px fixed it. Go figure!

**Comment by z3cka** [comment]
confirmed working in QA on `www-test`

**Comment by jameswilson** [comment]
I just checked this locally after my merge and its still problematic for me.

Using the "ipad" setting in Chrome Developer tools:

screenshot 2016-08-25 16 31 32

Using the "responsive" setting in Developer tools to dynamically resize the menu:

uclalib-menus

If things are working for you in upstream on your test environment, then I suggest we tweak the rest of the responsive display inside our mobile-responsive branch, where we can tweak the media queries.  We can continue discussion and review on https://bluespark.atlassian.net/browse/UCLALIB-225

**Comment by emb03** [comment]
there were two PRs #310 and #311

**Comment by jameswilson** [comment]
Yep, And i've got them both in my local branch, so something is still funky here.  no worries, we'll address it on our branch.

**Comment by z3cka** [comment]
ya, I see #310 and #311 as temp fixes for the current version of the site. The responsive effort can now use this as a base and address the wrapping down stream as needed.

**Comment by emb03** [comment]
This is what I see using Chrome ipad dev tools
screen shot 2016-08-25 at 2 44 04 pm

**Comment by z3cka** [comment]
right, `www-test` does not have the responsive WIP :-)

**Comment by z3cka** [comment]
So #310 and #311 can be deployed, @jameswilson and company now have this as a baseline to work from.

**Pull request merged**
