### PR TITLE
DRUP-683: Adds role "Lead Site Editor" and proper permissions

### PR DESCRIPTION
**Pull request by z3cka**
* also removes devel module as a dependency so we can turn devel off in production. Devel perms can still be set for the Administration role, but feature will no longer define that configuration; hense the removal of the dependency.
 * #ready #comment lead site editors, after you see a comment that test is ready; please try to delete a page on www-test

@akohler please deploy to test.

### CODE REVIEW

**Comment by akohler** [comment]
@z3cka : I see this removes linkchecker permissions from the uclalib_users feature as well.  Are these permissions being added to the uclalib_linkchecker feature - that's where they belong now, but until that's done those permissions will disappear.

**Comment by z3cka** [comment]
@akohler good catch, I was going to ask you about that. I did not intentionally remove them. I'm happy to roll those into `uclalib_linkchecker` ... would you like me to add that to this pull request?

**Comment by akohler** [comment]
@z3cka No, uclalib_linkchecker can be updated separately (unless you want to do it right now).  Let me know if I should proceed with #55  or wait.

**Comment by z3cka** [comment]
@akohler okay let's do it separately. I can roll it tomorrow. I kinda want to see what happens on test without it. I don't think the linkchecker perms will disappear, just not tracked in code *(but I've been wrong once ;-)*).

**Comment by akohler** [comment]
@z3cka OK, #55 merged and deployed to www-test; uclalib_users feature reverted.  linkchecker perms are no longer in code, but you're right - they still exist within www-test, just need to be exported into the uclalib_linkchecker feature.

**Pull request merged**
