### PR TITLE
DRUP-755: Security patches for core and ctools

### PR DESCRIPTION
**Pull request by akohler**
@z3cka See https://jira.library.ucla.edu/browse/DRUP-755 for links to release notes.  Please review, merge if/when ready for me to move to www-test.  I hope we can test and move to prod this weekend.  Thanks.

### CODE REVIEW

**Comment by z3cka** [comment]
I didn't have time to test this yet. I have some orcid stuff that needs to go to production before 9/8, so we can test early next week and deploy midweek or next Sat. 

Sorry, code4lib ate up my day today.

**Comment by akohler** [comment]
No problem, just let me know when ready for www-test, next week is fine.

**Comment by akohler** [comment]
@z3cka Do you expect we can deploy this PR this weekend?  Or do you need more time to review?  Can we put it on www-test yet?

**Comment by z3cka** [comment]
I can deploy now to test and will review there... I just didn't want it there for a meeting yesterday.

**Comment by z3cka** [comment]
pulling to test now

**Comment by z3cka** [comment]
deployment to www-test finished. I'm working with Elaine on some Staff Directory stuff and will be testing the update along with that. I will create PRs for those pieces to go to stage/prod over the weekend.

**Comment by z3cka** [comment]
Everything looks good on local and test environments; I can make a new PR(s) for the things to go to prod tomorrow night.

**Pull request merged**
